# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: bom|utf-8

title: Дубинкина Е.Ю.
description: >- # this means to ignore newlines until "baseurl:"
  Описание сайта
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
phone: +7 960 821 02 05
email: dubinkinaelen@yandex.ru
address: Россия, Самара, 443017, Заводское шоссе, 13А
instagram: https://www.instagram.com/?hl=ru
vk: https://vk.com/
facebook: https://ru-ru.facebook.com/

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - src/
  - package.json
  - package-lock.json
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

top_menu:
  - url: /
    name: Главная
  - url: /services/
    name: Услуги
  - url: /about/
    name: О компании
  - url: /contacts/
    name: Контакты

collections:
  posts:
    # output: true
    permalink: /:title/
  services:
    output: true
    permalink: /services/:path/
